### ISSUE TITLE
サーバ側のバリデーションの結果をフロントで使用したい

### ISSUE THREAD

**Issue by technote-space** [frouriojs/frourio#126]
## Description

バリデーションに関連した自動生成されるコードが以下のようになっており、 class-validator でのエラー をフロントでも表示させる方法がわかりません。

```ts
const createValidateHandler = (validators: (req: FastifyRequest) => (Promise<void> | null)[]): preValidationHookHandler =>
  (req, reply) => Promise.all(validators(req)).catch(() => reply.code(400).send())
```

とりあえず node_modules の dist を 直接以下のように書き換えて試したところうまく動作させることができました。
```ts
const createValidateHandler = (validators: (req: FastifyRequest) => (Promise<void> | null)[]): preValidationHookHandler =>
  (req, reply) => Promise.all(validators(req)).catch(error => reply.code(400).send(error))
```

https://user-images.githubusercontent.com/39912269/103201983-9b720500-4934-11eb-97d2-b394ea056c8e.mov

## Describe the solution you'd like

createValidateHandler でエラーを返してほしい

## Describe alternatives you've considered

フロント側でも class-validator によるバリデーションを行いその結果を使用するなど
ただサーバ側でしか確認が難しいようなバリデーション（保存されている他のレコードによるバリデーションなど）はかなり難しくなりそうなのでできればサーバ側の結果を使用したいです。

**Comment by solufa** [comment]
@technote-space 

要望投稿ありがとうございます
v0.22.0 でエラー情報をフロントに返却するように改善しました
serverディレクトリでfrourioのみアップデートしてお試しください

**Comment by technote-space** [comment]
確認しました。対応ありがとうございます！
