### ISSUE TITLE
TypeORMの挙動が開発環境と本番環境で違う挙動になる

### ISSUE THREAD

**Issue by uttk** [frouriojs/frourio#163]
## Description

TypeORMを用いている環境で `yarn build` してからサーバーを実行する( `yarn start` )と、以下のようなエラーが発生します。

※ 開発環境( `yarn dev` )では動くことを前提としています。

```shell
QueryFailedError: ER_NO_SUCH_TABLE: Table 'sample_database.a' doesn't exist
...
```

## Environment

- **Package version:**
  
  `v0.24.1`
- **OS:**
  
  - [x] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  `v12.18.4`
- **npm version:**
  
  `v6.14.6`

### 原因

今回の問題は、webpackがエンティティのクラス名まで圧縮してしまって、エンティティ名が変更されたままTypeORMに渡されている事が原因となっているようです。

### 解決策

https://scrapbox.io/dojineko/TypeORM_と_Webpack_を併用する場合の注意点

上記の記事を参考に、webpackの `minimize` オプションを `false` にする事で解決します。

```js
// server/webpack.config.js

const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin')
const nodeExternals = require('webpack-node-externals')
const NodemonPlugin = require('nodemon-webpack-plugin')

module.exports = {
  entry: './index.ts',
  target: 'node',

  // 以下の部分を追加
  optimization: {
    minimize: false
  },

  node: {
    __dirname: false
  },
  output: {
    filename: 'index.js',
    path: __dirname
  },
  module: {
    rules: [{ test: /\.ts$/, loader: 'ts-loader' }]
  },
  plugins: [new NodemonPlugin()],
  resolve: {
    extensions: ['.ts', '.js'],
    plugins: [new TsconfigPathsPlugin()]
  },
  externals: [nodeExternals()]
}
```

**Comment by LumaKernel** [comment]
ご報告ありがとうございます。こちら、create-frourio-app のほうで反映しており、あたらしく ボイラープレートから生成した場合は設定が反映された状態になると思います。それ以前に生成された分に関しては、提示してもらったように、webpack.config.js を手動で編集して貰えればと思います。

https://github.com/frouriojs/create-frourio-app/issues/157

**Comment by uttk** [comment]
@LumaKernel 

了解しました。対応ありがとうございます🙏
