### ISSUE TITLE
Should we use eslint-plugin-prettier?

### ISSUE THREAD

**Issue by yantene** [frouriojs/frourio#164]
## Description

Prettier is no longer officially recommending the use of eslint-plugin-prettier.

https://prettier.io/docs/en/integrating-with-linters.html

Frourio is using eslint-plugin-prettier.
What are the future plans for this project?

## Describe the solution you'd like

ESLint and Prettier may need to be run in separate npm scripts.

**Comment by solufa** [comment]
Thank you for posting.
We'll start with aspida and other libraries that frourio depends on.

**Comment by yantene** [comment]
Thanks for the reply.
frourio is fun to use. I'm really looking forward to this project in the future😆

**Comment by solufa** [comment]
@yantene 

Thank you for waiting.
Fixed npm scripts in create-frourio-app@0.28.0.
