### ISSUE TITLE
attachFieldsToBody is only valid in the promise api from fastify-multipart@4.0.5

### ISSUE THREAD

**Issue by bioflowy** [frouriojs/frourio#165]
## Description
attachFieldsToBody is only valid in the promise api from fastify-multipart@4.0.5.
As a result, build of the create-frourio-app fails.

> ERROR in ~/todo/server/$server.ts
./$server.ts 184:2-114
[tsl] ERROR in .../todo/server/$server.ts(184,3)
      TS2769: No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<FastifyMultipartOptions | FastifyMultipartAttactFieldsToBodyOptions, Server>, opts?: (RegisterOptions & FastifyMultipartOptions) | ... 2 more ... | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type 'boolean' is not assignable to type 'true'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifyMultipartOptions | FastifyMultipartAttactFieldsToBodyOptions, Server>, opts?: (RegisterOptions & FastifyMultipartOptions) | ... 2 more ... | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'FastifyPluginCallback<FastifyMultipartOptions | FastifyMultipartAttactFieldsToBodyOptions, Server>' is not assignable to parameter of type 'FastifyPluginAsync<FastifyMultipartOptions | FastifyMultipartAttactFieldsToBodyOptions, Server>'.
  Overload 3 of 3, '(plugin: FastifyPluginCallback<FastifyMultipartOptions | FastifyMultipartAttactFieldsToBodyOptions, Server> | FastifyPluginAsync<...> | Promise<...> | Promise<...>, opts?: (RegisterOptions & FastifyMultipartOptions) | ... 2 more ... | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type 'boolean' is not assignable to type 'true'.

Downgrading fastify-multipart@4.0.4 will result in a successful build

## Environment

- **Package version:**
  `v0.24.1 `
- **OS:**
  
  - [x] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  `v14.16.1`
- **npm version:**
  
  `6.14.12`

## Additional context

[fastify-multipart v4.0.5](https://github.com/fastify/fastify-multipart/releases/tag/v4.0.5)

**Comment by solufa** [comment]
@bioflowy 

Thank you for the report.
Fixed in create-frourio-app@0.28.0.
