### ISSUE TITLE
ServerResponseのbodyとheadersの型がanyになる

### ISSUE THREAD

**Issue by technote-space** [frouriojs/frourio#170]
## Description

![スクリーンショット 2021-06-06 18 39 38](https://user-images.githubusercontent.com/39912269/120919832-92147200-c6f6-11eb-8920-c976ef09cbfc.png)

```ts
type ServerResponse<K extends AspidaMethodParams> =
  | (K extends { resBody: K['resBody']; resHeaders: K['resHeaders'] }
  ? BaseResponse<K['resBody'], K['resHeaders'], K['status']>
  : K extends { resBody: K['resBody'] }
  ? PartiallyPartial<BaseResponse<K['resBody'], K['resHeaders'], K['status']>, 'headers'>
  : K extends { resHeaders: K['resHeaders'] }
  ? PartiallyPartial<BaseResponse<K['resBody'], K['resHeaders'], K['status']>, 'body'>
  : PartiallyPartial<
      BaseResponse<K['resBody'], K['resHeaders'], K['status']>,
      'body' | 'headers'
    >)
  | PartiallyPartial<BaseResponse<any, any, HttpStatusNoOk>, 'body' | 'headers'>
```

の定義の以下が原因

`| PartiallyPartial<BaseResponse<any, any, HttpStatusNoOk>, 'body' | 'headers'>`

status が HttpStatusNoOk かそれ以外かが決まっていないため `BaseResponse<any, any, HttpStatusNoOk>` の any になりうる

#### 「HttpStatusNoOk では body と headers がない」と定義する

`| BaseResponse<never, never, HttpStatusNoOk>`

正常系で普通に body を取得するときは resBody に定義した型を取得

![スクリーンショット 2021-06-06 18 48 35](https://user-images.githubusercontent.com/39912269/120920055-d3595180-c6f7-11eb-95d9-5e33d6b3369c.png)

ステータスを絞れば never

![スクリーンショット 2021-06-06 19 05 54](https://user-images.githubusercontent.com/39912269/120920535-41067d00-c6fa-11eb-9780-8ef8e422ad76.png)

この場合、以前バリデーションエラーの400のときはエラーを返してもらうようにして頂いたのでその body を考慮したりする必要があるかも知れません。
`Promise.all(validators(req)).catch(err => reply.code(400).send(err))`

#### サンプルのテストでステータスを絞る

![スクリーンショット 2021-06-06 18 58 41](https://user-images.githubusercontent.com/39912269/120920336-3ac3d100-c6f9-11eb-815b-19fd4e50e15d.png)

status が HttpStatusNoOk でないならば現状のままでも型は取れるのでサンプルのテストコードを書き換えて可能であればドキュメントに記載

## Environment

- **Package version:**
  
  `vX.X.X`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  ``
- **npm version:**
  
  ``

**Comment by solufa** [comment]
非常に詳細に調べていただきありがとうございます。
答えを出すのにかなり時間がかかりましたが、画像のような絞り込みを記述することにしました
根本的な解決は aspida v2 をリリースしたあとなら実現できそうです
![image](https://user-images.githubusercontent.com/9402912/131259314-b4508f5c-5c91-496c-afd3-6d5ad627f41b.png)

**Comment by LumaKernel** [comment]
resolved by https://github.com/frouriojs/create-frourio-app/pull/263

Thank you!
