### ISSUE TITLE
$server.tsでTS2684: The 'this' context of type 'void' is not assignable to method's 'this' of type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>'.

### ISSUE THREAD

**Issue by sutefu23** [frouriojs/frourio#173]
## 概要
素晴らしいプロダクトをありがとうございます。
ちょこちょこ触ってみてたのですが（先日のオンラインイベントにも参加させて頂きました）、昨日本格的に実戦投入しようと開始しまして、最高の使い勝手に感動しています。

昨日next.jsで使ってみて、今日nuxt.jsでインストールしてみたところ、同じ環境なのに、なぜかnuxtだとバックエンドの$server.tsがWebPackのコンパイルでエラーがでるようです。
nextの時とこの部分のコードは同じようですが、何か違うのでしょうか。

## 環境
node v14.15.5
webpack 5.41.1

## エラーメッセージ
[tsl] ERROR in /root/kokolab2/server/$server.ts(129,42)
      TS2684: The 'this' context of type 'void' is not assignable to method's 'this' of type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>'.

型 'void' の 'this' コンテキストを型 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>' のメソッドの 'this' に割り当てることはできません。ts(2684)

```// prettier-ignore
const callParserIfExistsQuery = (parser: preValidationHookHandler): preValidationHookHandler => (req, reply, done) =>
  Object.keys(req.query as any).length ? parser(req, reply, done) : done()

**Comment by technote-space** [comment]
#172 と同じエラーのようです。

今すぐ動かしたい場合は、fastifyではなくExpressを使用するか
patch-package などで以下にパッチ (`parser(req, reply, done)` => `parser`) を当てれば動くかもしれません。
https://github.com/frouriojs/frourio/blob/c9fe414d6423cc8956da95c8c04bf8a67ec035e3/src/buildServerFile.ts#L188-L189

**Comment by solufa** [comment]
お待たせしました
@IshinoJun が修正してくれました
v0.25.1 にアップデートしてみてください

**Comment by sutefu23** [comment]
@technote-space さま
@solufa さま

ご対応誠にありがとうございます！！
無事いけました！

frourioは書いてて楽しいです。たくさん色々使わせていただきます！！
