### ISSUE TITLE
Support for GitLab-CI

### ISSUE THREAD

**Issue by ndcollins** [frouriojs/frourio#177]
## Description

Compatibility with GitLab repositories

## Describe the solution you'd like

Would be great to generate the .gitlab-ci.yml file for doing deployments from a GitLab repo. Ideally, would allow the option for defining multiple environments (dev, integration, qa, prod, etc.)

**Comment by hashue** [comment]
I'm  sorry, but I can't accept your proposal.  
because I figure low merit for frourio side considering development cost.
