### ISSUE TITLE
一つのディレクトリに複数の動的ルーティングが置かれたらエラーを出す

### ISSUE THREAD

**Issue by solufa** [frouriojs/frourio#226]
## Description

```
hoge/
  _userId@number/...
  _userName@string/...
```

のとき、片方のコントローラが無効になって初心者が混乱すると思われる

$server.ts 生成時に気付けるはずなのでエラー出してあげたい

**Comment by LumaKernel** [comment]
closeされてるけど一応先に frourio-express 側の対応が必要です
まあ今からすぐやっちゃいます

**Comment by solufa** [comment]
Thanks!
