### ISSUE TITLE
Directory Level HookのpreHandrer関数内でawaitするとcontrollerが2回呼ばれる

### ISSUE THREAD

**Issue by humiyan02** [frouriojs/frourio#229]
## Description
Directory Level HookのpreHandrer関数内でawaitするとcontrollerが2回呼ばれてしまいます。
awaitを消すと直りますが、reqに値をセットできないので困っています。

## Environment

- **Package version:**
  
  `v0.27.1`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v14.18.1`

## Additional context
firebaseAuthのセッションクッキー検証の際に見つけました。
```
export default defineHooks(() => ({
  preHandler: async (req, res, done) => {
    console.log(req.url) // ここの時点で2回呼ばれる
    try {
      const sessionId = req.cookies.session
      const user = await firebaseAuth.verifySessionCookie(sessionId, true) // この行消すと直る
      if (user) {
        console.log('user:', user.uid)
        req.authUser = {
          userId: user.uid
        }
      } 
    } catch (err) {
        res.status(401).send()
    }finally{
       done() // 記載漏れ追記
    }
  }
}))


```

**Comment by humiyan02** [comment]
⇧
api/hooks.tsを消すと直りました！
```
import { defineHooks } from './$relay'

export default defineHooks(() => ({
  onRequest: async (req, reply, done) => {
    console.log('[request]:', req.url, 'query:', req.query, 'body:', req.body)
    done()
  }
}))
```

**Comment by humiyan02** [comment]
```
    console.log(req.url) // ここの時点で2回呼ばれる

```
が呼び出し1回になって直ったと思ったんですが、controllerはやはり2回呼ばれてました。。

**Comment by su8ru** [comment]
対応が遅くなり申し訳ありません。

`frourio`, `frourio-express` について、ご記載の `v0.27.1` および最新版の `v0.28.0` にて再現を試みているのですが、未だ確認できておらず、もう少し詳しい情報をいただければと思います。

1. サーバーは `express` ですか？それとも `fastify` ですか？
2. `onRequest` など別の Hooks でも発生しますか？それとも `preHandler` 限定ですか？

**Comment by humiyan02** [comment]
@su8ru 
対応ありがとうございます！

> サーバーは express ですか？それとも fastify ですか？

fastifyです！（すみません、伝えてませんでした。。）

> onRequest など別の Hooks でも発生しますか？それとも preHandler 限定ですか？

onRequest,preHandler,preValidationどれでも発生します。
preParsingはハンドラー関数の引数が合わずエラーになっていたので試していません。

参考
```
type Hooks = {
  onRequest?: AddedHandler<onRequestHookHandler> | AddedHandler<onRequestHookHandler>[]
  preParsing?: AddedHandler<preParsingHookHandler> | AddedHandler<preParsingHookHandler>[]
  preValidation?: AddedHandler<preValidationHookHandler> | AddedHandler<preValidationHookHandler>[]
  preHandler?: AddedHandler<preHandlerHookHandler> | AddedHandler<preHandlerHookHandler>[]
}
```

**Comment by humiyan02** [comment]
すみません、解決しました。

async関数にてdone()してしまっていたことが問題でした。
fastifyのドキュメントをしっかり見ればわかることでした。
関連Issue:https://github.com/fastify/fastify/issues/1511

対応ありがとうございました。
