### ISSUE TITLE
Cannot find module 'fastify-multipart' or its corresponding type declarations

### ISSUE THREAD

**Issue by humiyan02** [frouriojs/frourio#240]
`fastify-multipart`がdeprecatedとなっていたので、@fastify/multipartに変えたところ$server.tsにて
```
Cannot find module 'fastify-multipart' or its corresponding type declarations
```
https://www.npmjs.com/package/fastify-multipart
https://www.npmjs.com/package/@fastify/multipart

buildServerFile.tsにて`fastify-multipart`がハードコーディングされているのが原因っぽい？`fastify-multipart`→`@fastify/multipart`
https://github.com/frouriojs/frourio/blob/main/src/buildServerFile.ts#L46

とりあえず
```
    "fastify-multipart": "5.3.1",
    "@fastify/multipart": "^6.0.0",
```
を共存させて回避しています。

**Comment by LumaKernel** [comment]
一応
`npm i -D fastify-multipart@npm:@fastify/multipart@^6.0.0` で `$server.ts` 内の実装も置き換えられますかね。困っている方がいれば試してみていただけると。

対策について。
単純に置き換えるだけで良いのだろうか？それは breaking change のように思える。
もしbreakingにするぐらいならいっそ `@frourio/fastify-multipart` と書いておいて、上記の書き方を必須にすることも考えられる。
しかし fastify-multipart だけなのでとっとと置き換えてしまってもいいようにも見える。

**Comment by LumaKernel** [comment]
書き換えで採用しよう。マイナーアプデとします。

逆に5系を使い続ける必要がある場合は、

`npm i -D @fastify/multipart@npm:fastify-multipart@バージョン`

での対応をお願いします。
