### ISSUE TITLE
Sapper has been archived, so will you remove it ?

### ISSUE THREAD

**Issue by AzizulSami** [frouriojs/frourio#256]
Hi, Sapper GitHub page is read only now. So will you remove it ? Maybe replace it with another framework ?

**Comment by solufa** [comment]
Frourio itself does not depend on any specific front-end framework.

Your question is for create-frourio-app.
https://github.com/frouriojs/create-frourio-app

Sapper will remove it soon.
I have no plans to replace it with an alternative framework.
