### ISSUE TITLE
controller.tsでZodObjectのtypeをexportし、index.tsでimportするとtypecheckでエラーになる

### ISSUE THREAD

**Issue by humiyan02** [frouriojs/frourio#276]
## Description
controller.tsでZodObjectのtypeをexportし、index.tsでimportするとtypecheckでエラーになる

controller.ts
```js
const Hoge = z.object({
  hoge: z.string()
})
export type HogeType = z.infer<typeof Hoge>
```
index.ts
```js
import {HogeType} from "./controller"
```

試したこと
- zod以外の型のexportは正常
- zodオブジェクトのexportは正常
- zodオブジェクトから生成した型をexportするのも正常

## Environment

- **Package version:**
  
  `v0.31.0`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v16.15.0`
- **npm version:**
  
  `8.3.0`

## Additional context

```
"zod": "3.19.1"
```

**Comment by solufa** [comment]
@humiyan02 
すみません、このIssueの存在に気が付くのが遅れました

typecheckエラーは確かに再現できました
私の場合はindex.tsより先にcontroller.tsの型が評価されることでFastifyプラグインの型がanyになってしまうものでした

index.tsがcontroller.tsを参照することは想定していないので回避策としては同じディレクトリに
`validator.ts`
```ts
export const Hoge = z.object({
  hoge: z.string()
})
export type HogeType = z.infer<typeof Hoge>
```
というファイルを作ってindex.tsとcontroller.tsそれぞれでimportすることです
