### ISSUE TITLE
Broken links to images in README.md

### ISSUE THREAD

**Issue by arx-8** [frouriojs/frourio#277]
## Description

Could you please correct the broken links in the following images? It's a minor issue, but it doesn't look good and I would be a little hesitant to recommend this package to others.
https://github.com/frouriojs/frourio/blob/v0.31.1/README.md#why-frourio-

![image](https://user-images.githubusercontent.com/14254931/212469712-14427ea2-11fb-41f6-872c-98edc887e0e6.png)

Btw, I have just started the tutorial, but I am very impressed with a very well done framework. Thank you for publishing the great product!

## Environment

- **Package version:**
  `v0.31.1`
- **OS:**
  
  - [ ] Linux
  - [x] Windows
  - [x] macOS
- **Node.js version:**
  `N/A`
- **npm version:**
  `N/A`

## Additional context

N/A

**Comment by su8ru** [comment]
Thanks for the report!

It seems that when we recently made the website ([frourio.com](https://frourio.com)) compatible with the dark theme, the image references were broken. We'll be fixing that shortly, so please bear with us a little longer...!

If you would like, please consider using [frourio.com](https://frourio.com) in your recommendations. It will make it look better, even if only at first.
