### ISSUE TITLE
Feature Request: Global Hook ( or Request Properties ) Definition Support

### ISSUE THREAD

**Issue by LumaKernel** [frouriojs/frourio#94]
## Description

I understand each request object passed to endpoints is actually `Fastify`'s `Request`.
And we can append some properties with `hooks.ts` with defining exported types.
It may not be about the hooks feature itself. I'm new in Fastify, sorry.

For example, do authentication for all routes under `api/...` and adding `req.user` property if authenticated or `undefined` otherwise. This property may not only depending headers, but also cookies, sessions, ... and some they are not currently provided by `req` for api endpoints (in type level).

Now, it seems we should write the definition for all endpoints.

I'm using the workaround to define the utility `getUser(req: {params: unknown}) => UserProfile | undefined` for now.

## Describe the solution you'd like / Describe alternatives you've considered

My ideas are...

1. Use like the files `server/api/global-hooks.ts` ( or `**.d.ts` ) for defining global hooks ( or types only ).
2. `servere/api/some/cascading-hooks.ts` for all sub-directories.
3. Make `req` type definition intersected with `Request`.
4. Change `req` type to an interface as extensible definition ( I'm wondering it would be really working well or not... )
5. Providing the way to access raw req officially.

## Additional context

Descriptions example is almost my real case.

(off-topic: I appreciate this project... I had made a similar type generator for my private project, so I fell in love with this project.. And I want to celebrate for the Fastify version release.  )

( Ah, I'm sorry if it is aspida issue... )

**Comment by LumaKernel** [comment]
Maybe, the concrete settings become like below for my case.

```ts
// server.ts

// ...
fastify.register(csrf, csrfOptions);
fastify.register(auth);

fastify.after(() => {
  fastify.register(
    (fastify, _, done) => {
      fastify.addHook(
        'preHandler',
        fastify.auth([
          (req, _, done) => {
            const user = /* authentication */;

            req.user = user;
            done();
          },
        ]),
      );
      fastify.addHook('onRequest', fastify.csrfProtection);
      server(fastify);
      done();
    },
    {
      prefix: '/api',
    },
  );
});
// ...
```

```ts
// plugins/my-user-plugin.d.ts
import 'fastify';
declare module 'fastify' {
  interface FastifyRequest {
    user: { id: string } | null | undefined;
  }
}
```

I want an ability to extending `req` in API Endpoints.

**Comment by solufa** [comment]
@LumaKernel 

Thank you for posting this.
I will work on and implement a solution as soon as I can.

**Comment by solufa** [comment]
@LumaKernel 

Changed req to be extended by exporting AdditionalRequest in hooks.ts.

Also, the hooks in hooks.ts are cascading, so /server/api/hooks.ts is effectively Global Hooks.

Hooks written in contoller.ts do not cascade and are only available to that controller.

Does this fix solve your problem?

`/server/api/hooks.ts`

```ts
import { defineHooks } from './$relay'
import { getUserIdByToken } from '$/service/user'

export type AdditionalRequest = {
  user: {
    id: string
  },
  cookie?: string
}

export default defineHooks((fastify) => ({
  preHandler: fastify.auth([
    (req, _, done) => {
      const user =
        typeof req.headers.token === 'string' &&
        getUserIdByToken(req.headers.token)

      if (user) {
        req.user = user // req.user was added by AdditionalRequest
        done()
      } else {
        done(new Error('Unauthorized'))
      }
    }
  ])
}))
```

**Comment by LumaKernel** [comment]
Sorry for being late, looks nice to me! Thank you!
