### ISSUE TITLE
Feature Request ? ( or bug ): hooks.ts is not recognized if there is no method on that point.

### ISSUE THREAD

**Issue by LumaKernel** [frouriojs/frourio#96]
## Description

`<path>/hooks.ts` is only recognized if there are methods in `<path>/index.ts`.
Now, `hooks.ts` is used for subdirectories, for example,  methods in `<path>/sub/index.ts`.
Do you think is it needed to add one or more api methods only for enabling `hooks.ts`?

## Describe the solution you'd like / Describe alternatives you've considered

Just recognize `hooks.ts` even if there is no method on that point.

I think it's around here https://github.com/frouriojs/frourio/blob/master/src/createControllersText.ts#L185-L185 .

Thank you!

**Comment by solufa** [comment]
Thanks for the post.
It has been fixed and released!
